
spring:
  application:
    name: fegin-a
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8001
logging:
  level:
    org.springframework.cloud.openfeign: debug
    feign: debug

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full


